name: Deploy Privacy Policy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create HTML files
        run: |
          mkdir -p _site

          # Convert Korean markdown to HTML
          cat > _site/privacy-policy-ko.html << 'EOF'
          <!DOCTYPE html>
          <html lang="ko">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>개인정보처리방침 - E.S.C</title>
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; color: #333; }
              h1, h2, h3 { color: #2c3e50; border-bottom: 2px solid #e74c3c; padding-bottom: 10px; }
              h1 { font-size: 2.5em; text-align: center; }
              h2 { font-size: 1.8em; margin-top: 40px; }
              h3 { font-size: 1.3em; margin-top: 30px; }
              .meta { text-align: center; color: #7f8c8d; margin-bottom: 40px; }
              ul { padding-left: 20px; }
              li { margin-bottom: 8px; }
              .highlight { background-color: #f8f9fa; padding: 15px; border-left: 4px solid #e74c3c; margin: 20px 0; }
              hr { border: none; border-top: 1px solid #ecf0f1; margin: 40px 0; }
              @media (max-width: 600px) { body { padding: 10px; } h1 { font-size: 2em; } }
            </style>
          </head>
          <body>
          EOF

          # Convert markdown content to HTML (simple conversion)
          sed 's/^# \(.*\)$/<h1>\1<\/h1>/' privacy-policy-ko.md | \
          sed 's/^## \(.*\)$/<h2>\1<\/h2>/' | \
          sed 's/^### \(.*\)$/<h3>\1<\/h3>/' | \
          sed 's/^\*\*\([^*]*\)\*\*/<strong>\1<\/strong>/g' | \
          sed 's/^\- \(.*\)$/<li>\1<\/li>/' | \
          sed 's/^$/<br>/' | \
          sed 's/시행일자: \(.*\)$/<div class="meta">시행일자: \1<\/div>/' >> _site/privacy-policy-ko.html

          echo '</body></html>' >> _site/privacy-policy-ko.html

          # Convert English markdown to HTML
          cat > _site/privacy-policy-en.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Privacy Policy - E.S.C</title>
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; color: #333; }
              h1, h2, h3 { color: #2c3e50; border-bottom: 2px solid #e74c3c; padding-bottom: 10px; }
              h1 { font-size: 2.5em; text-align: center; }
              h2 { font-size: 1.8em; margin-top: 40px; }
              h3 { font-size: 1.3em; margin-top: 30px; }
              .meta { text-align: center; color: #7f8c8d; margin-bottom: 40px; }
              ul { padding-left: 20px; }
              li { margin-bottom: 8px; }
              .highlight { background-color: #f8f9fa; padding: 15px; border-left: 4px solid #e74c3c; margin: 20px 0; }
              hr { border: none; border-top: 1px solid #ecf0f1; margin: 40px 0; }
              @media (max-width: 600px) { body { padding: 10px; } h1 { font-size: 2em; } }
            </style>
          </head>
          <body>
          EOF

          sed 's/^# \(.*\)$/<h1>\1<\/h1>/' privacy-policy-en.md | \
          sed 's/^## \(.*\)$/<h2>\1<\/h2>/' | \
          sed 's/^### \(.*\)$/<h3>\1<\/h3>/' | \
          sed 's/^\*\*\([^*]*\)\*\*/<strong>\1<\/strong>/g' | \
          sed 's/^\- \(.*\)$/<li>\1<\/li>/' | \
          sed 's/^$/<br>/' | \
          sed 's/Effective Date: \(.*\)$/<div class="meta">Effective Date: \1<\/div>/' >> _site/privacy-policy-en.html

          echo '</body></html>' >> _site/privacy-policy-en.html

          # Create index.html
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="ko">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>E.S.C Privacy Policy</title>
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; max-width: 600px; margin: 50px auto; padding: 20px; text-align: center; }
              h1 { color: #2c3e50; margin-bottom: 40px; }
              .btn { display: inline-block; padding: 15px 30px; margin: 10px; background-color: #e74c3c; color: white; text-decoration: none; border-radius: 8px; font-weight: bold; transition: background-color 0.3s; }
              .btn:hover { background-color: #c0392b; }
              .description { color: #7f8c8d; margin-bottom: 40px; }
            </style>
          </head>
          <body>
            <h1>E.S.C (Escape Story Community)</h1>
            <div class="description">개인정보처리방침</div>
            <div>
              <a href="privacy-policy-ko.html" class="btn">한국어 🇰🇷</a>
              <a href="privacy-policy-en.html" class="btn">English 🇺🇸</a>
            </div>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4